import type { Phase } from '~/types';

export const PHASES_DATA: Phase[] = [
  // ═══════════════════════════════════════════════════════════
  // FASE 1: O DESPERTAR
  // ═══════════════════════════════════════════════════════════
  {
    id: 1,
    title: 'O Despertar',
    subtitle: 'Hidratação e Início',
    focus: 'Sair da inércia com metas simples.',
    icon: 'wb_sunny',
    gradient: 'from-amber-500 to-orange-600',
    totalXp: 500,
    missions: [
      {
        id: 1,
        type: 'teoria',
        title: 'Água ao Acordar',
        description: 'Descubra a importância de beber água ao acordar.',
        icon: 'auto_stories',
        xp: 30,
        question: 'Qual o principal benefício de beber água ao acordar?',
        quizOptions: [
          'Acelera o metabolismo e reidrata o corpo após o sono',
          'Elimina totalmente a necessidade de café da manhã',
          'Faz o corpo queimar gordura instantaneamente',
        ],
        correctAnswer: 0,
        instructions: 'A água ao acordar reidrata o corpo após horas de sono, acelera o metabolismo em até 24%, ajuda a eliminar toxinas e prepara o sistema digestivo para o dia. Seu corpo perde água durante o sono através da respiração e transpiração — repor esse líquido logo cedo é essencial para manter o equilíbrio hídrico.',
      },
      {
        id: 2,
        type: 'pratica',
        title: 'Hidratação Matinal',
        description: 'Beba 500ml de água assim que levantar.',
        icon: 'water_drop',
        xp: 40,
        instructions: 'Ao levantar, antes de qualquer coisa, beba 500ml de água (dois copos cheios). Dica: deixe uma garrafa cheia ao lado da cama na noite anterior para facilitar.',
      },
      {
        id: 3,
        type: 'pratica',
        title: 'Polichinelos Rápidos',
        description: 'Realize 20 polichinelos em qualquer momento do dia.',
        icon: 'directions_run',
        xp: 50,
        instructions: 'Em qualquer momento do seu dia, faça 20 polichinelos. Mantenha os braços esticados e os pés juntos ao iniciar. Salte abrindo as pernas e elevando os braços simultaneamente. Complete os 20 com boa postura!',
      },
      {
        id: 4,
        type: 'teoria',
        title: 'O Prato Colorido',
        description: 'Aprenda o conceito do Prato Colorido para uma alimentação saudável.',
        icon: 'palette',
        xp: 30,
        question: 'Por que devemos variar as cores dos alimentos no prato?',
        quizOptions: [
          'Apenas para o prato ficar mais bonito na foto',
          'Cada cor representa diferentes vitaminas e minerais essenciais',
          'Alimentos coloridos têm menos calorias que os brancos',
        ],
        correctAnswer: 1,
        instructions: 'O Prato Colorido é um conceito nutricional que sugere incluir alimentos de diferentes cores em cada refeição. Cada cor representa grupos diferentes de vitaminas e minerais: vermelho (licopeno), verde (ferro e fibras), amarelo (vitamina C), roxo (antocianinas), branco (alicina). Quanto mais colorido seu prato, mais nutrientes diversos você está consumindo.',
      },
      {
        id: 5,
        type: 'pratica',
        title: 'Refeição Colorida',
        description: 'Tire uma foto de uma refeição que contenha pelo menos 3 cores.',
        icon: 'photo_camera',
        xp: 40,
        instructions: 'Prepare ou escolha uma refeição que tenha pelo menos 3 cores diferentes de alimentos naturais. Por exemplo: arroz branco + feijão marrom + salada verde + tomate vermelho. Tire uma foto e observe a diversidade no seu prato!',
      },
      {
        id: 6,
        type: 'pratica',
        title: 'Caminhada Leve',
        description: 'Caminhe por 10 minutos em ritmo leve.',
        icon: 'directions_walk',
        xp: 50,
        instructions: 'Saia para uma caminhada tranquila de 10 minutos. Pode ser no bairro, num parque ou até dentro de casa. O objetivo é apenas movimentar o corpo — sem pressa, sem exigência de velocidade.',
      },
      {
        id: 7,
        type: 'teoria',
        title: 'Sono e Emagrecimento',
        description: 'Descubra por que o sono ajuda no processo de emagrecimento.',
        icon: 'bedtime',
        xp: 30,
        question: 'O que acontece com o corpo quando dormimos pouco?',
        quizOptions: [
          'O corpo entra em modo econômico e gasta menos energia',
          'Aumenta o cortisol e a grelina, causando mais fome por alimentos calóricos',
          'O metabolismo acelera para compensar o cansaço',
        ],
        correctAnswer: 1,
        instructions: 'Durante o sono profundo, o corpo libera o hormônio do crescimento (GH), que ajuda a queimar gordura e reparar tecidos. A privação de sono aumenta o cortisol (hormônio do estresse) e a grelina (hormônio da fome), fazendo você sentir mais fome por alimentos calóricos. Dormir bem regula o apetite, melhora a recuperação muscular e mantém o metabolismo funcionando corretamente.',
      },
      {
        id: 8,
        type: 'pratica',
        title: 'Desligamento Digital',
        description: 'Desligue telas 30 minutos antes de dormir.',
        icon: 'phonelink_off',
        xp: 40,
        instructions: 'Hoje à noite, desligue ou afaste TODAS as telas (celular, TV, tablet, computador) pelo menos 30 minutos antes de deitar. A luz azul emitida por esses dispositivos inibe a produção de melatonina, o hormônio do sono. Use esse tempo para ler um livro, meditar ou apenas relaxar.',
      },
      {
        id: 9,
        type: 'pratica',
        title: 'Agachamentos Livres',
        description: 'Faça 10 agachamentos livres (sem peso).',
        icon: 'fitness_center',
        xp: 50,
        instructions: 'Fique em pé com os pés na largura dos ombros. Desça como se fosse sentar em uma cadeira invisível, mantendo as costas retas e os joelhos alinhados com os pés. Desça até as coxas ficarem paralelas ao chão (ou o máximo que conseguir). Suba de volta. Repita 10 vezes!',
      },
      {
        id: 10,
        type: 'desafio_final',
        title: 'Caminhada Contínua',
        description: 'Complete 15 minutos de caminhada contínua sem parar.',
        icon: 'emoji_events',
        xp: 140,
        instructions: 'Este é seu primeiro Desafio Final! Caminhe por 15 minutos seguidos, sem parar, em ritmo constante. Escolha um lugar agradável e mantenha o foco. Esse é o começo da sua jornada!',
        subTasks: [
          'Aqueça com 1 minuto parado, girando os braços',
          'Caminhe 15 minutos sem parar',
          'Finalize com 1 minuto de respiração profunda',
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // FASE 2: NUTRIÇÃO CONSCIENTE
  // ═══════════════════════════════════════════════════════════
  {
    id: 2,
    title: 'Nutrição Consciente',
    subtitle: 'Comer Bem para Viver Bem',
    focus: 'Pequenas trocas alimentares e lanches.',
    icon: 'restaurant',
    gradient: 'from-emerald-500 to-teal-600',
    totalXp: 550,
    missions: [
      {
        id: 1,
        type: 'teoria',
        title: 'Fome Física vs Emocional',
        description: 'Entenda a diferença entre fome física e fome emocional.',
        icon: 'psychology',
        xp: 30,
        question: 'Como identificar a fome emocional?',
        quizOptions: [
          'Surge gradualmente e aceita qualquer alimento',
          'Surge de repente, pede comidas específicas e está ligada a emoções',
          'Acontece sempre nos mesmos horários do dia',
        ],
        correctAnswer: 1,
        instructions: 'A fome física surge gradualmente, pode ser saciada com qualquer alimento, vem acompanhada de sinais como estômago roncando, e desaparece quando estamos satisfeitos. A fome emocional surge de repente, pede alimentos específicos (geralmente calóricos), está ligada a emoções (tédio, ansiedade, tristeza), e não desaparece mesmo após comer.',
      },
      {
        id: 2,
        type: 'pratica',
        title: 'Teste da Água',
        description: 'Identifique um momento de fome emocional e beba água em vez de comer.',
        icon: 'water_drop',
        xp: 40,
        instructions: 'Hoje, quando sentir vontade de beliscar algo fora de hora, pare e se pergunte: "Estou realmente com fome ou é emocional?". Se for emocional, beba um copo d\'água cheio e espere 10 minutos. Muitas vezes, a sede é confundida com fome.',
      },
      {
        id: 3,
        type: 'teoria',
        title: 'Macronutrientes',
        description: 'Conheça os macronutrientes: Proteína, Carboidrato e Gordura.',
        icon: 'science',
        xp: 30,
        question: 'Qual macronutriente fornece mais calorias por grama?',
        quizOptions: [
          'Proteínas (4 kcal/g)',
          'Carboidratos (4 kcal/g)',
          'Gorduras (9 kcal/g)',
        ],
        correctAnswer: 2,
        instructions: 'Macronutrientes são os três pilares da alimentação:\n\n• Proteínas (4 kcal/g): Constroem e reparam músculos, pele, cabelo. Fontes: frango, ovos, tofu, feijão.\n\n• Carboidratos (4 kcal/g): Principal fonte de energia do corpo e do cérebro. Fontes: arroz, pão, batata, frutas.\n\n• Gorduras (9 kcal/g): Essenciais para hormônios, absorção de vitaminas e proteção dos órgãos. Fontes: azeite, abacate, castanhas.\n\nTodos os três são necessários — o segredo está no equilíbrio.',
      },
      {
        id: 4,
        type: 'pratica',
        title: 'Fruta no Lanche',
        description: 'Coma uma fruta no lanche da tarde.',
        icon: 'nutrition',
        xp: 40,
        instructions: 'No lanche da tarde de hoje, em vez de biscoitos, salgadinhos ou doces, coma uma fruta. Pode ser banana, maçã, laranja, manga — a que preferir. Frutas são ricas em vitaminas, fibras e antioxidantes.',
      },
      {
        id: 5,
        type: 'pratica',
        title: 'Polichinelos em Séries',
        description: 'Faça 3 séries de 10 polichinelos com 1 minuto de descanso.',
        icon: 'directions_run',
        xp: 50,
        instructions: 'Realize 3 séries de 10 polichinelos, descansando 1 minuto entre cada série. Isso é treinar com "séries e descanso" — um conceito fundamental do treinamento estruturado. Mantenha boa postura e ritmo!',
      },
      {
        id: 6,
        type: 'teoria',
        title: 'Açúcar Refinado',
        description: 'Entenda por que devemos evitar o açúcar refinado.',
        icon: 'warning',
        xp: 30,
        question: 'O que o açúcar refinado causa no corpo?',
        quizOptions: [
          'Fornece energia sustentável e duradoura para o dia todo',
          'Eleva rapidamente a glicose no sangue, seguido de queda brusca que causa mais fome',
          'Fortalece o sistema imunológico por ser rico em vitaminas',
        ],
        correctAnswer: 1,
        instructions: 'O açúcar refinado eleva rapidamente a glicose no sangue (pico glicêmico), seguido de uma queda brusca que causa mais fome e cansaço. O consumo excessivo está associado a: resistência à insulina, ganho de peso, inflamação crônica, diabetes tipo 2 e problemas cardiovasculares. Ele também não oferece nenhum nutriente — são "calorias vazias".',
      },
      {
        id: 7,
        type: 'pratica',
        title: 'Dia Sem Refrigerante',
        description: 'Passe o dia sem consumir refrigerantes ou sucos industrializados.',
        icon: 'no_drinks',
        xp: 50,
        instructions: 'O desafio de hoje é simples: passe o dia inteiro sem beber refrigerantes ou sucos de caixinha/garrafa. Substitua por água, água com limão, chá natural ou suco feito em casa. Um copo de refrigerante pode ter até 35g de açúcar (7 colheres de chá)!',
      },
      {
        id: 8,
        type: 'pratica',
        title: 'Alongamento de Pernas',
        description: 'Realize 5 minutos de alongamento para as pernas.',
        icon: 'accessibility_new',
        xp: 40,
        instructions: 'Alongue seus membros inferiores por 5 minutos. Sugestões:\n• Toque os dedos dos pés (posterior de coxa): 30s cada perna\n• Agachado segurando nos tornozelos (adutores): 30s\n• Posição de corredor com joelho no chão (flexor de quadril): 30s cada lado\n• Sentado, puxe o pé em direção ao glúteo (quadríceps): 30s cada lado',
      },
      {
        id: 9,
        type: 'teoria',
        title: 'Lendo Rótulos',
        description: 'Aprenda a ler a lista de ingredientes nos rótulos dos alimentos.',
        icon: 'document_scanner',
        xp: 30,
        question: 'Como saber se um alimento tem muito açúcar pelo rótulo?',
        quizOptions: [
          'Se a embalagem for colorida e atrativa',
          'Se o açúcar aparece entre os 3 primeiros ingredientes da lista',
          'Se o produto é vendido na seção de doces do mercado',
        ],
        correctAnswer: 1,
        instructions: 'Dicas para ler rótulos como um profissional:\n\n1. Ordem importa: Os ingredientes são listados do maior para o menor em quantidade. Se açúcar está nos 3 primeiros, evite.\n\n2. Nomes disfarçados: Açúcar pode aparecer como: xarope de milho, maltodextrina, dextrose, sacarose.\n\n3. Menos é mais: Quanto menos ingredientes, geralmente mais natural o alimento.\n\n4. Se não conseguir pronunciar, provavelmente é um aditivo químico.\n\n5. Tabela nutricional: Verifique calorias, proteínas, sódio e açúcar por porção (atenção ao tamanho da porção!).',
      },
      {
        id: 10,
        type: 'desafio_final',
        title: 'Lanche Natural',
        description: 'Prepare um lanche saudável usando apenas ingredientes naturais.',
        icon: 'emoji_events',
        xp: 160,
        instructions: 'Hora do Desafio Final da Fase 2! Prepare um lanche saudável usando APENAS ingredientes naturais (nada industrializado). Exemplos: wrap de alface com frango desfiado, smoothie de frutas com aveia, torradas integrais com abacate e ovo.',
        subTasks: [
          'Escolha uma receita simples com ingredientes naturais',
          'Prepare o lanche com suas próprias mãos',
          'Tire uma foto do resultado (opcional)',
          'Saboreie com atenção plena — sem celular!',
        ],
      },
    ],
  },
];

/** Tabela de fases resumida — usa as 100 fases do levelsSystem */
import { ALL_PHASES } from '~/utils/levelsSystem';

export const PHASES_OVERVIEW = ALL_PHASES.map(p => ({
  id: p.level,
  title: p.title,
  icon: p.icon,
  gradient: p.gradient,
}));
